apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
   
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 5000 #{{ .Values.backend.service.targetport }}
          volumeMounts:
            - name: shared-storage
              mountPath: /var/data
          command: ["/bin/sh"]
          args: ["-c", "cp -r /var/shared/* /var/data/ && flask run --host=0.0.0.0"]
        - name: nginx
          image: nginx:latest
          ports: 
            - containerPort: 80
          volumeMounts:
            - name: shared-storage
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: shared-storage
          emptyDir: {}
