name: UnitTest

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "hello github action"  
